# Generated by Django 3.2.3 on 2021-06-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210601_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/user/defaultavatar.jpg', upload_to='media/%Y/%m/%d'),
        ),
    ]
