# Generated by Django 3.2.3 on 2021-06-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210601_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
